version: "3"

services:
  web:
    container_name: project-flow-web
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

  db:
    container_name: project-flow-db
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
